# TODO: format whole file
# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

# import = [
# "~/.config/alacritty/catpuccin-mocha.toml",
# "~/.config/alacritty/keybindings.toml",
# ]

# [shell]
# program               = "/usr/bin/zsh"
# args                  = [ "--login", ]

# working_directory     = "None"
# live_config_reload    = true
# ipc_socket            = true

[env]
TERM                  = "xterm-256color"

[window]
dimensions            = { columns = 0, lines = 0 }
position              = "None"
padding               = { x = 0, y = 0 }
dynamic_padding       = true
decorations           = "Full"
opacity               = 0.80
blur                  = true
startup_mode          = "Windowed"
title                 = "Alacritty"
dynamic_title         = true
class                 = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments     = false
option_as_alt         = "Both"

[scrolling]
history               = 100000
multiplier            = 1

# [font]
# normal                = { family = "Solid Mono", style = "Regular" }
# bold                  = { family = "Solid Mono", style = "Bold" }
# italic                = { family = "Solid Mono", style = "Italic" }
# bold_italic           = { family = "Solid Mono", style = "Bold Italic" }
# size                  = 18
# offset                = { x = 0, y = 0 }
# glyph_offset          = { x = 0, y = 0 }
# builtin_box_drawing   = true


# catpuccin-mocha, ported from .yml
[colors.primary]
background            = "#1E1E2E"
foreground            = "#CDD6F4"
dim_foreground        = "#CDD6F4"
bright_foreground     = "#CDD6F4"

[colors.cursor]
text                  = "#1E1E2E"
cursor                = "#F5E0DC"

[colors.vi_mode_cursor]
text                  = "#1E1E2E"
cursor                = "#B4BEFE"

[colors.search.matches]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.search.focused_match]
foreground            = "#1E1E2E"
background            = "#A6E3A1"

[colors.hints.start]
foreground            = "#1E1E2E"
background            = "#F9E2AF"

[colors.hints.end]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.line_indicator]
#foreground            = "None"
#background            = "None"

[colors.footer_bar]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.selection]
text                  = "#1E1E2E"
background            = "#F5E0DC"

[colors.normal]
black                 = "#45475A"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#BAC2DE"

[colors.bright]
black                 = "#585B70"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#A6ADC8"

[colors.dim]
black                 = "#45475A"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#BAC2DE"

[colors]
indexed_colors = [
  { index = 16, color = "#FAB387" },
  { index = 17, color = "#F5E0DC" },
]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[bell]
animation             = "Linear"
duration              = 300
color                 = "#2086df"
command               = "None"

[selection]
semantic_escape_chars = ""
save_to_clipboard     = false

[cursor.style]
shape                 = "Underline"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Underline"
blinking              = "Always"

[cursor]
blink_interval        = 600
blink_timeout         = 0
unfocused_hollow      = false
thickness             = 0.10

[terminal]
osc52                 = "Disabled"

[mouse]
hide_when_typing      = false
bindings = []

[hints]
alphabet              = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks            = true
post_processing       = true
persist               = false
mouse.enabled         = true
binding               = { key = "S", mods = "Control" }
regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "0", mods = "Control|Shift", action = "ResetFontSize" },
  { key = "PageUp", action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" },
  { key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp" },
  { key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown" },
  { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
  { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
  { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
  { key = "H", mods = "Control|Shift|Alt", action = "ClearHistory" },
  #{ key = "", mods = "Control|Shift", action = "Hide" },
  #{ key = "", mods = "Control|Shift", action = "Minimize" },
  #{ key = "", mods = "Control|Shift", action = "Quit" },
  { key = "L", mods = "Control|Shift|Alt", action = "ClearLogNotice" },
  #{ key = "", mods = "Control|Shift", action = "SpawnNewInstance" },
  #{ key = "", mods = "Control|Shift", action = "CreateNewWindow" },
  #{ key = "", mods = "Control|Shift", action = "ToggleFullscreen" },
  #{ key = "", mods = "Control|Shift", action = "ToggleMaximized" },
  #{ key = "", mods = "Control|Shift", action = "ClearSelection" },
  { key = "I", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward" },
  #{ key = "", mods = "Control|Shift", action = "CopySelection" },
  { key = "Insert", mods = "Control|Shift", action = "PasteSelection" },

  # TODO: configure vi mode keybindings
]


[debug]
render_timer          = false
persistent_logging    = false
log_level             = "Warn"
renderer              = "None"
print_events          = false
highlight_damage      = false
prefer_egl            = false

